
# Triggers
on:
  push :
    branches :
      - master

# Functions
jobs:
  # Build Job
  build:
    # Name of the job
    name: Build
    # The OS to run the job on
    runs-on: ubuntu-latest
    # Steps
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install node 18
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install NPM Dependencies
        run: npm i

      - name: Build Project
        run: npm run build

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}  

      - name: Build Docker Image
        run: docker build -t rubenjacob23/react-app .

      - name: Publish image to docker hub
        run: docker push rubenjacob23/react-app:latest

  deploy: 
    needs: build
    runs-on: aws-ec2    
    steps:      
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Delete Old Container
        run: docker rm -f reactContainer
      - name: Remove existing Docker image on ec2
        run: docker rmi -f rubenjacob23/react-app:latest || true
      - name: Pull image from docker hub
        run: docker pull rubenjacob23/react-app:latest      
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name reactContainer rubenjacob23/react-app 
      


